/* AcuTing OS — 我的臨床筆記 (personal clinical notes).

   Why this exists (Ting, 2026-07-30): the sourced content answers "what do the
   textbooks say"; it cannot hold "what I saw in clinic". Those are different
   kinds of truth and must not be mixed — a note like 「這穴對我的長期胃痛病人
   效果比書上寫的好」 has no source URL and never should. So notes live in their
   own layer, on the same card, clearly marked as hers rather than sourced.

   Design decisions, and why:

   - NEVER written into data/**.json. Those files carry provenance and are
     regenerated by scripts/build-data.js; a personal note in there would either
     be destroyed by the next build or would pollute sourced records with
     unsourceable content. Notes go to localStorage, same as RV1 verdicts
     (js/review.js) and clinical cases.
   - Keyed by `kind:id` (point:ST36, herb:herb.he_tao_ren,
     formula:formula.ma_huang_tang). Ids are immutable per DECISIONS D2, so a
     note stays attached even when the record's content is rewritten — which is
     exactly what happens during the current card-quality passes.
   - Export/import is not optional. localStorage is per-browser and gets wiped
     by "clear site data"; clinical observations accumulated over months of
     study are not something to lose to a cache clear. Export writes a JSON
     file she can keep or commit.
   - Notes may contain patient-adjacent observations, so the export is labelled
     as private and is NOT the same file as the review-verdict export (which is
     explicitly safe-to-commit knowledge data). Keep the two separate. */
(function () {
  "use strict";

  const STORE_KEY = "acuting-clinical-notes-v1";
  const STORE_VERSION = 1;

  const KIND_LABEL = {
    point: { zh: "穴位", en: "Point" },
    herb: { zh: "中藥", en: "Herb" },
    formula: { zh: "方劑", en: "Formula" }
  };

  function esc(value) {
    return String(value == null ? "" : value).replace(/[&<>"']/g, (ch) => ({
      "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;"
    })[ch]);
  }

  /* 唯讀鎖:讀不到就不准寫。
   *
   * 舊版讀取失敗時 console.warn 後回傳空 store,於是每張卡顯示「尚未記錄」,
   * 而下一次 setNote → writeStore 會把整份**還救得回來的原始位元組**永久蓋掉。
   * clinical-store.js 明文禁止這一招並記著真實事故(2026-08-11 演練),
   * 臨床筆記層當時沒有套用同一條規則。
   *
   * 現在:壞掉 = 進唯讀,寫入路徑一律拒絕,並且畫面上說得出原因。
   * 錯誤訊息不轉述 parser 內容 —— JSON.parse 的訊息會內嵌一段原始輸入,
   * 而這一份原始輸入是臨床筆記(同 clinical-store 的 PHI 邊界規則)。 */
  let storeLocked = null;   // null = 正常;字串 = 唯讀原因

  function readStore() {
    const raw = localStorage.getItem(STORE_KEY);
    if (raw === null || raw === "") { storeLocked = null; return { version: STORE_VERSION, notes: {} }; }
    let parsed;
    try {
      parsed = JSON.parse(raw);
    } catch {
      storeLocked = `筆記庫無法解析(${raw.length} 個字元,內容不轉述)。已進入唯讀保護:在修好之前不會寫入,以免蓋掉還救得回來的原始資料。`;
      return { version: STORE_VERSION, notes: {}, __locked: true };
    }
    if (!parsed || typeof parsed !== "object" || !parsed.notes || typeof parsed.notes !== "object") {
      storeLocked = "筆記庫存在但形狀不對(缺少 notes)。已進入唯讀保護,不會寫入。";
      return { version: STORE_VERSION, notes: {}, __locked: true };
    }
    storeLocked = null;
    return parsed;
  }

  function writeStore(store) {
    if (store && store.__locked) throw new Error(storeLocked || "筆記庫唯讀保護中");
    try {
      localStorage.setItem(STORE_KEY, JSON.stringify(store));
    } catch (err) {
      // 配額滿 / 無痕模式:過去這個例外會從 click handler 拋出去,
      // 「已儲存」那行永遠跑不到 —— 使用者看到的是「按了沒反應」。
      throw new Error(`筆記寫入失敗,資料尚未儲存:${err && err.message ? err.message : err}`);
    }
  }

  function storeLockReason() { return storeLocked; }

  const keyOf = (kind, id) => `${kind}:${id}`;

  function noteFor(kind, id) {
    return readStore().notes[keyOf(kind, id)] || null;
  }

  function setNote(kind, id, text, displayName) {
    const store = readStore();
    const key = keyOf(kind, id);
    const body = String(text == null ? "" : text).trim();
    if (!body) {
      delete store.notes[key];            // empty note = no note, not a blank record
    } else {
      const existing = store.notes[key];
      store.notes[key] = {
        kind,
        id,
        display_name: displayName || existing?.display_name || id,
        text: body,
        created_at: existing?.created_at || new Date().toISOString(),
        updated_at: new Date().toISOString()
      };
    }
    writeStore(store);
    return store.notes[key] || null;
  }

  const allNotes = () => Object.values(readStore().notes)
    .sort((a, b) => String(b.updated_at).localeCompare(String(a.updated_at)));

  /* ---------- rendering ---------- */

  const isEnglish = () => document.body?.dataset?.contentMode === "english";

  function formatStamp(iso) {
    if (!iso) return "";
    try {
      const d = new Date(iso);
      const pad = (n) => String(n).padStart(2, "0");
      return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())} ${pad(d.getHours())}:${pad(d.getMinutes())}`;
    } catch (err) {
      return "";
    }
  }

  /* Returns the notes panel for one record. Collapsed when empty so it costs
     one line on a card that already has a lot on it, and auto-open when a note
     exists — a note she wrote is worth more screen space than a sourced field,
     because it is the part no source can replace. */
  function panel(kind, id, displayName) {
    if (!kind || !id) return "";
    const en = isEnglish();
    const note = noteFor(kind, id);
    const kindLabel = KIND_LABEL[kind] || { zh: "紀錄", en: "Record" };
    const title = en ? "My Clinical Notes" : "我的臨床筆記";
    const hint = en
      ? `Your own observations for this ${kindLabel.en.toLowerCase()} — private, stored on this device, never mixed into sourced content.`
      : `你自己對這個${kindLabel.zh}的觀察與心得 —— 私人、存在本機，不會混入有來源的內容。`;
    const placeholder = en
      ? "e.g. dose that worked, patient response, what to watch for, how it differed from the textbook…"
      : "例如：實際有效的劑量、病人反應、要注意什麼、和書上寫的差異…";

    return `
      <details class="clinical-note" data-note-kind="${esc(kind)}" data-note-id="${esc(id)}" data-note-display-name="${esc(displayName || id)}"${note ? " open" : ""}>
        <summary class="clinical-note__summary">
          <span class="clinical-note__title">📝 ${esc(title)}</span>
          ${note
            ? `<span class="clinical-note__badge">${en ? "saved" : "已記錄"} · ${esc(formatStamp(note.updated_at))}</span>`
            : `<span class="clinical-note__badge is-empty">${en ? "add a note" : "尚未記錄"}</span>`}
        </summary>
        <div class="clinical-note__body">
          <p class="clinical-note__hint">${esc(hint)}</p>
          <textarea class="clinical-note__input" rows="5"
            data-note-input
            aria-label="${esc(title)}"
            placeholder="${esc(placeholder)}">${esc(note?.text || "")}</textarea>
          <div class="clinical-note__actions">
            <button type="button" class="clinical-note__save" data-note-save>${en ? "Save note" : "儲存筆記"}</button>
            <span class="clinical-note__status" data-note-status aria-live="polite"></span>
            ${note ? `<button type="button" class="clinical-note__delete" data-note-delete>${en ? "Delete" : "刪除"}</button>` : ""}
          </div>
          ${note?.created_at && note.created_at !== note.updated_at
            ? `<p class="clinical-note__meta">${en ? "First written" : "初次記錄"}: ${esc(formatStamp(note.created_at))}</p>`
            : ""}
        </div>
      </details>
    `;
  }

  /* One delegated listener for the whole app: the panel is re-rendered inside
     several different card templates (point / herb / formula), so per-panel
     listeners would be re-bound on every re-render and leak. */
  function bind() {
    document.addEventListener("click", (event) => {
      const root = event.target.closest?.(".clinical-note");
      if (!root) return;
      const kind = root.dataset.noteKind;
      const id = root.dataset.noteId;
      const input = root.querySelector("[data-note-input]");
      const status = root.querySelector("[data-note-status]");
      const en = isEnglish();

      // 存/刪都可能失敗(唯讀鎖、配額滿)。失敗時絕不顯示「已儲存」——
      // 那句話比沒有回饋更糟,她會以為寫進去了。
      const runWrite = (fn, okText) => {
        try {
          fn();
          if (status) { status.textContent = okText; status.classList.remove("is-error"); }
          return true;
        } catch (err) {
          if (status) { status.textContent = String(err && err.message ? err.message : err); status.classList.add("is-error"); }
          else alert(String(err && err.message ? err.message : err));
          return false;
        }
      };

      if (event.target.closest("[data-note-save]")) {
        // Read the name off the panel itself. It used to look for an ancestor
        // carrying the attribute, found none, and fell back to the raw id — so
        // every saved note was labelled "herb.ma_huang" instead of "麻黃 Ma
        // Huang", which matters because the export is the only place the notes
        // are read outside the card.
        const displayName = root.dataset.noteDisplayName || "";
        if (!runWrite(() => setNote(kind, id, input?.value || "", displayName), en ? "Saved" : "已儲存")) return;
        root.querySelector(".clinical-note__badge")?.classList.remove("is-empty");
        document.dispatchEvent(new CustomEvent("acuting:note-saved", { detail: { kind, id } }));
        return;
      }

      if (event.target.closest("[data-note-delete]")) {
        if (!runWrite(() => setNote(kind, id, ""), en ? "Deleted" : "已刪除")) return;
        if (input) input.value = "";
        document.dispatchEvent(new CustomEvent("acuting:note-saved", { detail: { kind, id } }));
      }
    });

    // Ctrl/Cmd+Enter saves without reaching for the mouse — these get written
    // mid-study, so the interaction has to be cheap.
    document.addEventListener("keydown", (event) => {
      if (!(event.ctrlKey || event.metaKey) || event.key !== "Enter") return;
      const input = event.target.closest?.("[data-note-input]");
      if (!input) return;
      input.closest(".clinical-note")?.querySelector("[data-note-save]")?.click();
    });
  }

  function exportNotes() {
    const notes = allNotes();
    const payload = {
      dataset: "acuting_clinical_notes",
      exported_at: new Date().toISOString(),
      privacy: "PRIVATE — personal clinical observations. Review before sharing or committing; may contain patient-adjacent detail.",
      version: STORE_VERSION,
      count: notes.length,
      notes
    };
    const blob = new Blob([JSON.stringify(payload, null, 2)], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `acuting-clinical-notes-${new Date().toISOString().slice(0, 10)}.json`;
    a.click();
    URL.revokeObjectURL(url);
    return payload;
  }

  function importNotes(json, { merge = true } = {}) {
    /* 唯讀鎖:不論 merge 與否都先問一次。
     *
     * merge:true 走 readStore(),拿回來的物件帶 __locked,writeStore 會擋。
     * 但 merge:false 建的是一個全新的 store 物件,身上沒有 __locked —— 那條路
     * 會把還救得回來的原始位元組永久蓋掉,正是 storeLocked 當初要防的事故。
     * 匯入是唯一從 UI 進得來的整批寫入,所以這道閘門放在函式最上面。 */
    readStore();
    if (storeLocked) throw new Error(storeLocked);
    let parsed;
    try {
      parsed = typeof json === "string" ? JSON.parse(json) : json;
    } catch (err) {
      throw new Error("Not valid JSON");
    }
    const incoming = Array.isArray(parsed?.notes) ? parsed.notes : null;
    if (!incoming) throw new Error("No `notes` array in file");
    const store = merge ? readStore() : { version: STORE_VERSION, notes: {} };
    let added = 0;
    incoming.forEach((n) => {
      if (!n?.kind || !n?.id || !n?.text) return;
      const key = keyOf(n.kind, n.id);
      const existing = store.notes[key];
      // On conflict keep whichever was edited more recently rather than
      // silently overwriting work that only exists on one device.
      if (existing && String(existing.updated_at || "") > String(n.updated_at || "")) return;
      store.notes[key] = n;
      added += 1;
    });
    writeStore(store);
    return { added, total: Object.keys(store.notes).length };
  }

  /* ---------- 檔案進出 UI(凍結例外,Ting 2026-09-12) ----------

     她的原話:「我想上課先在 local 先儲存一些筆記(穴位),然後之後你幫我更新」。
     上面的 exportNotes()/importNotes() 2026-07-30 就寫好了,但**全庫沒有任何
     地方呼叫它們** —— 只有開 DevTools 打指令才叫得到。也就是說她課堂上寫的
     筆記實際上出不了那台瀏覽器,而那正是她唯一要求的流程。這一段就是補這個洞:
     一顆按鈕出檔案,一個檔案選擇器進來。

     還有一件她完全無法自己看出來的事,所以狀態列刻意把它印出來:
     localStorage 是綁 origin 的,而 **origin 包含 port**。
     `http://localhost:8663` 與 `http://localhost:8361` 是兩個不同的櫃子。
     她下一堂課用另一個 port 起 dev server,上一堂課的筆記就「不見了」——
     其實一個字都沒少,只是這個 origin 看不到。那一行 origin 不是裝飾,
     它是她唯一能自己看懂發生什麼事的線索。

     這一層不做伺服器同步、不寫 data/**、不碰病歷的 localStorage。 */

  /* 上次匯出時間存自己的 key。不塞進筆記 store:store 的形狀就是匯出檔的形狀,
     多一個欄位會流進檔案、再流回來,污染資料層(而且會被當成一則壞筆記)。 */
  const EXPORT_META_KEY = "acuting-notes-export-meta-v1";

  /* 門檻 2 天。病歷那邊是 7 天(app.js BACKUP_STALE_DAYS),筆記比它短,三個理由:
     (1) 筆記只有一份副本,病歷至少還有歷次匯出的歷史檔;
     (2) 一堂課能累積十幾則,兩天就足以累積到「重寫一次會很痛」;
     (3) 她的流程本身就是「課後把筆記帶到網站」—— 隔兩天還沒帶過去,
         就是這個流程卡住了,值得在畫面最上面說一句。
     再短會變成天天叫(她本來就會連著幾天上課),再長就失去提醒的意義。 */
  const EXPORT_STALE_DAYS = 2;

  const t = (zh, en) => (isEnglish() ? en : zh);

  /* file:// 開啟時 location.origin 是字串 "null" —— 那種情況印 href 才看得懂。 */
  const originLabel = () =>
    (location.origin && location.origin !== "null") ? location.origin : location.href;

  function readExportMeta() {
    try {
      const parsed = JSON.parse(localStorage.getItem(EXPORT_META_KEY) || "null");
      if (parsed && typeof parsed === "object") return parsed;
    } catch (err) { /* 壞掉/無痕:當成「從未匯出」。這個 meta 是提醒用的,不是資料,
                       重算沒有損失 —— 而方向是安全的(會多提醒,不會少提醒)。 */ }
    return { lastExportAt: null, lastExportCount: null, lastExportOrigin: null };
  }

  function writeExportMeta(meta) {
    try { localStorage.setItem(EXPORT_META_KEY, JSON.stringify(meta)); return true; }
    catch (err) { return false; }   // 寫不進去 = 橫幅繼續提醒,方向安全
  }

  function exportAgeDays(meta) {
    if (!meta || !meta.lastExportAt) return Infinity;
    const ms = Date.now() - new Date(meta.lastExportAt).getTime();
    return Number.isFinite(ms) ? ms / 86400000 : Infinity;
  }

  /* 上次匯出之後才改過的筆記。橫幅只根據這個數字出現,所以「匯出完什麼都沒寫」
     不會在兩天後再被叫一次。 */
  function pendingNotes() {
    const since = readExportMeta().lastExportAt;
    return allNotes().filter((n) => !since || String(n.updated_at || "") > String(since));
  }

  function transferSummary() {
    const store = readStore();
    const locked = storeLockReason();
    const meta = readExportMeta();
    return {
      locked,
      count: locked ? null : Object.keys(store.notes).length,
      pending: locked ? null : pendingNotes().length,
      lastExportAt: meta.lastExportAt || null,
      lastExportCount: Number.isFinite(meta.lastExportCount) ? meta.lastExportCount : null,
      origin: originLabel()
    };
  }

  /* 匯出。回傳 {ok, message} —— 失敗時 ok:false,呼叫端**絕不**顯示成功字樣。
     三種一定要擋下來的失敗:
       - 唯讀鎖:此時 readStore() 回空 store,照著匯出會產生一個「0 則」的檔案,
         而那個檔案看起來跟「真的沒有筆記」一模一樣 —— 最糟的失敗形狀。
       - 0 則:不下載空檔,直接說這個來源沒有東西。
       - Blob/URL 例外:訊息照實說「檔案沒有產生」。 */
  function runExport() {
    const locked = (readStore(), storeLockReason());
    if (locked) {
      return { ok: false, message: t(
        `不能匯出:${locked}`,
        `Cannot export: ${locked}`) };
    }
    const total = Object.keys(readStore().notes).length;
    if (!total) {
      return { ok: false, message: t(
        `這個來源(${originLabel()})目前沒有任何筆記,沒有東西可以匯出。如果你記得寫過,很可能是寫在另一個網址或 port 上 —— 換 port 等於換一個儲存空間。`,
        `No notes on this source (${originLabel()}), so there is nothing to export. If you remember writing some, they are probably on another URL or port — a different port is a different storage space.`) };
    }
    let payload;
    try {
      payload = exportNotes();
    } catch (err) {
      return { ok: false, message: t(
        `匯出失敗,檔案沒有產生:${err && err.message ? err.message : err}`,
        `Export failed, no file was produced: ${err && err.message ? err.message : err}`) };
    }
    writeExportMeta({
      lastExportAt: payload.exported_at,
      lastExportCount: payload.count,
      lastExportOrigin: originLabel()
    });
    /* 用「已產生」而不是「已下載」:瀏覽器的下載封鎖(或沙箱)攔掉 a.click() 時
       這裡收不到任何訊號,宣告「已下載」就是宣告我們量不到的事。 */
    return { ok: true, message: t(
      `已產生匯出檔(${payload.count} 則):acuting-clinical-notes-${payload.exported_at.slice(0, 10)}.json。若瀏覽器沒有出現下載,檢查下載封鎖設定後再按一次 —— 上次匯出時間已更新為現在。`,
      `Export file produced (${payload.count} notes): acuting-clinical-notes-${payload.exported_at.slice(0, 10)}.json. If no download appeared, check your browser's download blocking and press again — the last-export time is already set to now.`) };
  }

  /* 匯入。新增與更新分開數:importNotes 的 added 把「新增」和「覆蓋較舊的本機版」
     算在一起,而她需要知道的是「這次帶進來幾則新的」。 */
  function runImport(text) {
    const before = new Set(allNotes().map((n) => keyOf(n.kind, n.id)));
    let result;
    try {
      result = importNotes(text, { merge: true });
    } catch (err) {
      return { ok: false, message: t(
        `匯入失敗,筆記庫沒有被改動:${err && err.message ? err.message : err}`,
        `Import failed, the notes store was not changed: ${err && err.message ? err.message : err}`) };
    }
    let incoming = null;
    try {
      const parsed = JSON.parse(text);
      if (Array.isArray(parsed && parsed.notes)) incoming = parsed.notes.length;
    } catch (err) { /* 走到這裡 importNotes 已經成功,所以解析不會失敗;
                       真的失敗就少報一個數字,不影響已經寫進去的內容。 */ }
    const after = allNotes();
    const created = after.filter((n) => !before.has(keyOf(n.kind, n.id))).length;
    const updated = Math.max(0, result.added - created);
    const kept = incoming === null ? null : Math.max(0, incoming - result.added);
    let message = t(
      `已匯入到 ${originLabel()}:新增 ${created} 則、更新 ${updated} 則,目前共 ${result.total} 則。`,
      `Imported into ${originLabel()}: ${created} added, ${updated} updated, ${result.total} total.`);
    if (kept !== null) {
      message += t(
        `檔案裡有 ${incoming} 則${kept ? `,其中 ${kept} 則沒有寫入(本機版本較新,或那筆缺少 kind/id/內容)` : ""}。`,
        ` The file held ${incoming} note(s)${kept ? `; ${kept} were not written (the local copy is newer, or the entry lacked kind/id/text)` : ""}.`);
    }
    return { ok: true, message };
  }

  function showTransferStatus(result) {
    const host = document.getElementById("notesTransferStatus");
    if (!host) return;
    host.textContent = result.message;
    host.classList.toggle("is-error", !result.ok);
  }

  function renderTransferStatusLine() {
    const host = document.getElementById("notesStatusLine");
    if (!host) return;
    const s = transferSummary();
    const bits = [];
    bits.push(`${esc(t("目前來源", "Current source"))} <code>${esc(s.origin)}</code>`);
    bits.push(s.locked
      ? `<strong class="notes-transfer__locked">${esc(t("筆記庫唯讀保護中(筆數無法信任)", "Notes store is read-only (count cannot be trusted)"))}</strong>`
      : `<strong>${s.count}</strong> ${esc(t("則筆記", s.count === 1 ? "note" : "notes"))}`);
    bits.push(s.lastExportAt
      ? `${esc(t("上次匯出", "Last export"))} ${esc(formatStamp(s.lastExportAt))}${s.lastExportCount === null ? "" : `(${s.lastExportCount} ${esc(t("則", "notes"))})`}`
      : esc(t("從未匯出", "Never exported")));
    if (!s.locked && s.pending) {
      bits.push(`<strong class="notes-transfer__pending">${s.pending} ${esc(t("則尚未匯出", "not yet exported"))}</strong>`);
    }
    host.innerHTML = bits.join(" · ");

    const why = document.getElementById("notesLockReason");
    if (why) {
      why.textContent = s.locked || "";
      why.hidden = !s.locked;
    }
  }

  /* 置頂橫幅。形狀照 app.js renderBackupBanner()(病歷那條)—— 同一個問題、
     同一個提醒語法,只是換一層資料;顏色刻意不同,兩條橫幅同時出現時要分得出來。 */
  function renderExportBanner() {
    const existing = document.querySelector(".notes-reminder-banner");
    const s = transferSummary();
    // 唯讀時不提醒匯出:此時能匯出的是一份空檔,提醒她去做那件事是在幫倒忙。
    const stale = !s.locked && s.pending > 0
      && (!s.lastExportAt || exportAgeDays(readExportMeta()) >= EXPORT_STALE_DAYS);
    if (!stale) { if (existing) existing.remove(); return; }

    /* 橫幅上的數字會變(她又寫了兩則),所以已經存在時要**更新標籤**而不是
       early-return。病歷那條 renderBackupBanner() 是 `if (existing) return`,
       它印的是天數所以看起來沒事;這裡印的是筆數,照抄就會在畫面上留一個
       「有 1 則」而實際有 3 則的假數字。標籤放在自己的 span 裡,
       這樣重畫不會清掉旁邊那塊錯誤訊息(匯出失敗時只有它說得出原因)。 */
    const days = s.lastExportAt ? Math.floor(exportAgeDays(readExportMeta())) : null;
    const label = days === null
      ? t(`有 ${s.pending} 則臨床筆記從未匯出過`, `${s.pending} clinical note(s) have never been exported`)
      : t(`有 ${s.pending} 則臨床筆記在 ${days} 天前那次匯出之後有變更`,
          `${s.pending} clinical note(s) changed since the export ${days} day(s) ago`);
    const labelText = `📝 ${label}（${t("只存在這個來源", "stored only on this source")} ${s.origin}）— `;

    if (existing) {
      const labelEl = existing.querySelector("[data-notes-banner-label]");
      if (labelEl) labelEl.textContent = labelText;
      return;
    }

    const banner = document.createElement("div");
    banner.className = "notes-reminder-banner";
    const labelEl = document.createElement("span");
    labelEl.setAttribute("data-notes-banner-label", "");
    labelEl.textContent = labelText;
    banner.appendChild(labelEl);

    const bannerStatus = document.createElement("span");
    bannerStatus.className = "notes-reminder-banner__status";

    const btn = document.createElement("button");
    btn.type = "button";
    btn.textContent = t("立即匯出", "Export now");
    btn.addEventListener("click", () => {
      const result = runExport();
      showTransferStatus(result);
      // 失敗時把原因寫在橫幅上而不是只寫進面板:這顆按鈕按得到的地方可能不是
      // 首頁,面板那行她看不到 —— 看不到的錯誤等於靜默失敗。
      if (!result.ok) { bannerStatus.textContent = ` ${result.message}`; return; }
      renderNotesTransfer();
    });
    banner.appendChild(btn);

    const link = document.createElement("a");
    link.href = "#notesTransferPanel";
    link.textContent = t("筆記進出…", "Notes transfer…");
    banner.appendChild(link);

    banner.appendChild(bannerStatus);

    document.body.prepend(banner);
  }

  function renderNotesTransfer() {
    renderTransferStatusLine();
    renderExportBanner();
  }

  function bindTransfer() {
    document.addEventListener("click", (event) => {
      if (!event.target.closest || !event.target.closest("[data-notes-export]")) return;
      showTransferStatus(runExport());
      renderNotesTransfer();
    });

    document.addEventListener("change", (event) => {
      const input = event.target.closest && event.target.closest("[data-notes-import]");
      if (!input || !input.files || !input.files[0]) return;
      const file = input.files[0];
      const reader = new FileReader();
      reader.onerror = () => {
        showTransferStatus({ ok: false, message: t(
          `讀不到檔案「${file.name}」,筆記庫沒有被改動。`,
          `Could not read "${file.name}"; the notes store was not changed.`) });
        input.value = "";
      };
      reader.onload = () => {
        showTransferStatus(runImport(String(reader.result == null ? "" : reader.result)));
        input.value = "";   // 同一個檔案再選一次也要能觸發 change
        renderNotesTransfer();
        document.dispatchEvent(new CustomEvent("acuting:notes-imported"));
      };
      reader.readAsText(file);
    });

    // 卡片上存/刪一則就重畫狀態列與橫幅(筆數、尚未匯出數都會變)。
    document.addEventListener("acuting:note-saved", renderNotesTransfer);
    renderNotesTransfer();
  }

  window.AcuTingNotes = {
    panel,
    noteFor,
    setNote,
    allNotes,
    exportNotes,
    importNotes,
    count: () => Object.keys(readStore().notes).length,
    // 唯讀原因(null = 正常)。呼叫端可據此在畫面上說明為何不能寫。
    lockReason: () => { readStore(); return storeLockReason(); },
    // 檔案進出層:UI 用這三個,不要在別處重寫門檻與 origin 判斷。
    transferSummary,
    runExport,
    runImport,
    renderTransfer: renderNotesTransfer
  };

  function boot() { bind(); bindTransfer(); }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", boot, { once: true });
  } else {
    boot();
  }
})();
