/* AcuTing OS — 我的臨床筆記 (personal clinical notes).

   Why this exists (Ting, 2026-07-30): the sourced content answers "what do the
   textbooks say"; it cannot hold "what I saw in clinic". Those are different
   kinds of truth and must not be mixed — a note like 「這穴對我的長期胃痛病人
   效果比書上寫的好」 has no source URL and never should. So notes live in their
   own layer, on the same card, clearly marked as hers rather than sourced.

   Design decisions, and why:

   - NEVER written into data/**.json. Those files carry provenance and are
     regenerated by scripts/build-data.js; a personal note in there would either
     be destroyed by the next build or would pollute sourced records with
     unsourceable content. Notes go to localStorage, same as RV1 verdicts
     (js/review.js) and clinical cases.
   - Keyed by `kind:id` (point:ST36, herb:herb.he_tao_ren,
     formula:formula.ma_huang_tang). Ids are immutable per DECISIONS D2, so a
     note stays attached even when the record's content is rewritten — which is
     exactly what happens during the current card-quality passes.
   - Export/import is not optional. localStorage is per-browser and gets wiped
     by "clear site data"; clinical observations accumulated over months of
     study are not something to lose to a cache clear. Export writes a JSON
     file she can keep or commit.
   - Notes may contain patient-adjacent observations, so the export is labelled
     as private and is NOT the same file as the review-verdict export (which is
     explicitly safe-to-commit knowledge data). Keep the two separate. */
(function () {
  "use strict";

  const STORE_KEY = "acuting-clinical-notes-v1";
  const STORE_VERSION = 1;

  const KIND_LABEL = {
    point: { zh: "穴位", en: "Point" },
    herb: { zh: "中藥", en: "Herb" },
    formula: { zh: "方劑", en: "Formula" }
  };

  function esc(value) {
    return String(value == null ? "" : value).replace(/[&<>"']/g, (ch) => ({
      "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;"
    })[ch]);
  }

  /* 唯讀鎖:讀不到就不准寫。
   *
   * 舊版讀取失敗時 console.warn 後回傳空 store,於是每張卡顯示「尚未記錄」,
   * 而下一次 setNote → writeStore 會把整份**還救得回來的原始位元組**永久蓋掉。
   * clinical-store.js 明文禁止這一招並記著真實事故(2026-08-11 演練),
   * 臨床筆記層當時沒有套用同一條規則。
   *
   * 現在:壞掉 = 進唯讀,寫入路徑一律拒絕,並且畫面上說得出原因。
   * 錯誤訊息不轉述 parser 內容 —— JSON.parse 的訊息會內嵌一段原始輸入,
   * 而這一份原始輸入是臨床筆記(同 clinical-store 的 PHI 邊界規則)。 */
  let storeLocked = null;   // null = 正常;字串 = 唯讀原因

  function readStore() {
    const raw = localStorage.getItem(STORE_KEY);
    if (raw === null || raw === "") { storeLocked = null; return { version: STORE_VERSION, notes: {} }; }
    let parsed;
    try {
      parsed = JSON.parse(raw);
    } catch {
      storeLocked = `筆記庫無法解析(${raw.length} 個字元,內容不轉述)。已進入唯讀保護:在修好之前不會寫入,以免蓋掉還救得回來的原始資料。`;
      return { version: STORE_VERSION, notes: {}, __locked: true };
    }
    if (!parsed || typeof parsed !== "object" || !parsed.notes || typeof parsed.notes !== "object") {
      storeLocked = "筆記庫存在但形狀不對(缺少 notes)。已進入唯讀保護,不會寫入。";
      return { version: STORE_VERSION, notes: {}, __locked: true };
    }
    storeLocked = null;
    return parsed;
  }

  function writeStore(store) {
    if (store && store.__locked) throw new Error(storeLocked || "筆記庫唯讀保護中");
    try {
      localStorage.setItem(STORE_KEY, JSON.stringify(store));
    } catch (err) {
      // 配額滿 / 無痕模式:過去這個例外會從 click handler 拋出去,
      // 「已儲存」那行永遠跑不到 —— 使用者看到的是「按了沒反應」。
      throw new Error(`筆記寫入失敗,資料尚未儲存:${err && err.message ? err.message : err}`);
    }
  }

  function storeLockReason() { return storeLocked; }

  const keyOf = (kind, id) => `${kind}:${id}`;

  function noteFor(kind, id) {
    return readStore().notes[keyOf(kind, id)] || null;
  }

  function setNote(kind, id, text, displayName) {
    const store = readStore();
    const key = keyOf(kind, id);
    const body = String(text == null ? "" : text).trim();
    if (!body) {
      delete store.notes[key];            // empty note = no note, not a blank record
    } else {
      const existing = store.notes[key];
      store.notes[key] = {
        kind,
        id,
        display_name: displayName || existing?.display_name || id,
        text: body,
        created_at: existing?.created_at || new Date().toISOString(),
        updated_at: new Date().toISOString()
      };
    }
    writeStore(store);
    return store.notes[key] || null;
  }

  const allNotes = () => Object.values(readStore().notes)
    .sort((a, b) => String(b.updated_at).localeCompare(String(a.updated_at)));

  /* ---------- rendering ---------- */

  const isEnglish = () => document.body?.dataset?.contentMode === "english";

  function formatStamp(iso) {
    if (!iso) return "";
    try {
      const d = new Date(iso);
      const pad = (n) => String(n).padStart(2, "0");
      return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())} ${pad(d.getHours())}:${pad(d.getMinutes())}`;
    } catch (err) {
      return "";
    }
  }

  /* Returns the notes panel for one record. Collapsed when empty so it costs
     one line on a card that already has a lot on it, and auto-open when a note
     exists — a note she wrote is worth more screen space than a sourced field,
     because it is the part no source can replace. */
  function panel(kind, id, displayName) {
    if (!kind || !id) return "";
    const en = isEnglish();
    const note = noteFor(kind, id);
    const kindLabel = KIND_LABEL[kind] || { zh: "紀錄", en: "Record" };
    const title = en ? "My Clinical Notes" : "我的臨床筆記";
    const hint = en
      ? `Your own observations for this ${kindLabel.en.toLowerCase()} — private, stored on this device, never mixed into sourced content.`
      : `你自己對這個${kindLabel.zh}的觀察與心得 —— 私人、存在本機，不會混入有來源的內容。`;
    const placeholder = en
      ? "e.g. dose that worked, patient response, what to watch for, how it differed from the textbook…"
      : "例如：實際有效的劑量、病人反應、要注意什麼、和書上寫的差異…";

    return `
      <details class="clinical-note" data-note-kind="${esc(kind)}" data-note-id="${esc(id)}" data-note-display-name="${esc(displayName || id)}"${note ? " open" : ""}>
        <summary class="clinical-note__summary">
          <span class="clinical-note__title">📝 ${esc(title)}</span>
          ${note
            ? `<span class="clinical-note__badge">${en ? "saved" : "已記錄"} · ${esc(formatStamp(note.updated_at))}</span>`
            : `<span class="clinical-note__badge is-empty">${en ? "add a note" : "尚未記錄"}</span>`}
        </summary>
        <div class="clinical-note__body">
          <p class="clinical-note__hint">${esc(hint)}</p>
          <textarea class="clinical-note__input" rows="5"
            data-note-input
            aria-label="${esc(title)}"
            placeholder="${esc(placeholder)}">${esc(note?.text || "")}</textarea>
          <div class="clinical-note__actions">
            <button type="button" class="clinical-note__save" data-note-save>${en ? "Save note" : "儲存筆記"}</button>
            <span class="clinical-note__status" data-note-status aria-live="polite"></span>
            ${note ? `<button type="button" class="clinical-note__delete" data-note-delete>${en ? "Delete" : "刪除"}</button>` : ""}
          </div>
          ${note?.created_at && note.created_at !== note.updated_at
            ? `<p class="clinical-note__meta">${en ? "First written" : "初次記錄"}: ${esc(formatStamp(note.created_at))}</p>`
            : ""}
        </div>
      </details>
    `;
  }

  /* One delegated listener for the whole app: the panel is re-rendered inside
     several different card templates (point / herb / formula), so per-panel
     listeners would be re-bound on every re-render and leak. */
  function bind() {
    document.addEventListener("click", (event) => {
      const root = event.target.closest?.(".clinical-note");
      if (!root) return;
      const kind = root.dataset.noteKind;
      const id = root.dataset.noteId;
      const input = root.querySelector("[data-note-input]");
      const status = root.querySelector("[data-note-status]");
      const en = isEnglish();

      // 存/刪都可能失敗(唯讀鎖、配額滿)。失敗時絕不顯示「已儲存」——
      // 那句話比沒有回饋更糟,她會以為寫進去了。
      const runWrite = (fn, okText) => {
        try {
          fn();
          if (status) { status.textContent = okText; status.classList.remove("is-error"); }
          return true;
        } catch (err) {
          if (status) { status.textContent = String(err && err.message ? err.message : err); status.classList.add("is-error"); }
          else alert(String(err && err.message ? err.message : err));
          return false;
        }
      };

      if (event.target.closest("[data-note-save]")) {
        // Read the name off the panel itself. It used to look for an ancestor
        // carrying the attribute, found none, and fell back to the raw id — so
        // every saved note was labelled "herb.ma_huang" instead of "麻黃 Ma
        // Huang", which matters because the export is the only place the notes
        // are read outside the card.
        const displayName = root.dataset.noteDisplayName || "";
        if (!runWrite(() => setNote(kind, id, input?.value || "", displayName), en ? "Saved" : "已儲存")) return;
        root.querySelector(".clinical-note__badge")?.classList.remove("is-empty");
        document.dispatchEvent(new CustomEvent("acuting:note-saved", { detail: { kind, id } }));
        return;
      }

      if (event.target.closest("[data-note-delete]")) {
        if (!runWrite(() => setNote(kind, id, ""), en ? "Deleted" : "已刪除")) return;
        if (input) input.value = "";
        document.dispatchEvent(new CustomEvent("acuting:note-saved", { detail: { kind, id } }));
      }
    });

    // Ctrl/Cmd+Enter saves without reaching for the mouse — these get written
    // mid-study, so the interaction has to be cheap.
    document.addEventListener("keydown", (event) => {
      if (!(event.ctrlKey || event.metaKey) || event.key !== "Enter") return;
      const input = event.target.closest?.("[data-note-input]");
      if (!input) return;
      input.closest(".clinical-note")?.querySelector("[data-note-save]")?.click();
    });
  }

  function exportNotes() {
    const notes = allNotes();
    const payload = {
      dataset: "acuting_clinical_notes",
      exported_at: new Date().toISOString(),
      privacy: "PRIVATE — personal clinical observations. Review before sharing or committing; may contain patient-adjacent detail.",
      version: STORE_VERSION,
      count: notes.length,
      notes
    };
    const blob = new Blob([JSON.stringify(payload, null, 2)], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `acuting-clinical-notes-${new Date().toISOString().slice(0, 10)}.json`;
    a.click();
    URL.revokeObjectURL(url);
    return payload;
  }

  function importNotes(json, { merge = true } = {}) {
    let parsed;
    try {
      parsed = typeof json === "string" ? JSON.parse(json) : json;
    } catch (err) {
      throw new Error("Not valid JSON");
    }
    const incoming = Array.isArray(parsed?.notes) ? parsed.notes : null;
    if (!incoming) throw new Error("No `notes` array in file");
    const store = merge ? readStore() : { version: STORE_VERSION, notes: {} };
    let added = 0;
    incoming.forEach((n) => {
      if (!n?.kind || !n?.id || !n?.text) return;
      const key = keyOf(n.kind, n.id);
      const existing = store.notes[key];
      // On conflict keep whichever was edited more recently rather than
      // silently overwriting work that only exists on one device.
      if (existing && String(existing.updated_at || "") > String(n.updated_at || "")) return;
      store.notes[key] = n;
      added += 1;
    });
    writeStore(store);
    return { added, total: Object.keys(store.notes).length };
  }

  window.AcuTingNotes = {
    panel,
    noteFor,
    setNote,
    allNotes,
    exportNotes,
    importNotes,
    count: () => Object.keys(readStore().notes).length,
    // 唯讀原因(null = 正常)。呼叫端可據此在畫面上說明為何不能寫。
    lockReason: () => { readStore(); return storeLockReason(); }
  };

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", bind, { once: true });
  } else {
    bind();
  }
})();
